services:
  newsblur_web:
    hostname: nb.com
    container_name: newsblur_web
    image: newsblur/newsblur_${NEWSBLUR_BASE:-python3}:latest
    build:
      context: .
      dockerfile: docker/newsblur_base_image.Dockerfile
    # user: "${CURRENT_UID}:${CURRENT_GID}"
    environment:
      - DOCKERBUILD=True
      - RUNWITHMAKEBUILD=${RUNWITHMAKEBUILD:-True}
      - HTTP_PROXY=http://172.17.0.1:8881
      - HTTPS_PROXY=http://172.17.0.1:8881
      - NO_PROXY="127.0.0.1,localhost,::1,db_postgres,db_redis,db_elasticsearch,db_mongo,nginx,haproxy,dejavu,nb.vlakor.ru,172.17.0.1,172.17.0.0/16"
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - newsblur_db_mongo
      - newsblur_db_postgres
      - newsblur_db_redis
      - newsblur_db_elasticsearch
    ulimits:
      nproc: 10000
      nofile:
        soft: 10000
        hard: 10000
    ports:
      - 8000:8000
    # only use gunicorn if the TEST env variable is not "True"
    entrypoint: /bin/sh -c newsblur_web/entrypoint.sh
    volumes:
      - ${PWD}:/srv/newsblur
    labels:
      - glance.name=NewsBlur
      - glance.icon=di:newsblur
      - glance.url=https://nb.vlakor.ru
      - glance.description=RSS Reader
      - glance.id=newsblur

  newsblur_node:
    container_name: newsblur_node
    image: newsblur/newsblur_node:latest
    user: "${CURRENT_UID:-1000}:${CURRENT_GID:-1000}"
    environment:
      - NODE_ENV=docker
      - MONGODB_PORT=29019
      - HTTP_PROXY=http://172.17.0.1:8881
      - HTTPS_PROXY=http://172.17.0.1:8881
      - NO_PROXY="127.0.0.1,localhost,::1,db_postgres,db_redis,db_elasticsearch,db_mongo,nginx,haproxy,dejavu,nb.vlakor.ru,172.17.0.1,172.17.0.0/16"
    command: node newsblur.js
    restart: unless-stopped
    stop_signal: HUP
    depends_on:
      - newsblur_db_mongo
      - newsblur_db_postgres
      - newsblur_db_redis
    ports:
      - 8008:8008
    volumes:
      - ${PWD}/node:/srv
      - ${PWD}/node/originals:/srv/originals
    labels:
      - glance.parent=newsblur
      - glance.name=newsblur_node

  imageproxy:
    container_name: newsblur_imageproxy
    # image: ghcr.io/willnorris/imageproxy:latest # Enable if you don't need arm64 and want the original imageproxy
    image: yusukeito/imageproxy:v0.11.2 # Enable if you want arm64
    user: "${CURRENT_UID:-1000}:${CURRENT_GID:-1000}"
    entrypoint: /app/imageproxy -addr 0.0.0.0:8088 -cache /tmp/imageproxy -verbose
    restart: unless-stopped
    ports:
      - 8088:8088
    volumes:
      - /mnt/usbssd1/data/NewsBlur/tmp:/tmp/imageproxy
    labels:
      - glance.parent=newsblur
      - glance.name=newsblur_imageproxy

  nginx:
    container_name: newsblur_nginx
    image: nginx:1.19.6
    restart: unless-stopped
    ports:
      - 81:81
    depends_on:
      - newsblur_web
      - newsblur_node
      - newsblur_db_postgres
      - newsblur_db_redis
      - newsblur_db_mongo
      - newsblur_db_elasticsearch
    environment:
      - DOCKERBUILD=True
    volumes:
      - ./docker/nginx/nginx.local.conf:/etc/nginx/conf.d/nginx.conf
      - ${PWD}:/srv/newsblur
    labels:
      - glance.parent=newsblur
      - glance.name=newsblur_nginx

  newsblur_db_postgres:
    container_name: newsblur_db_postgres
    image: postgres:13.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=newsblur
      - POSTGRES_PASSWORD=newsblur
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U newsblur"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    ports:
      - 5434:5432
    volumes:
      - /mnt/usbssd1/data/NewsBlur/postgres:/var/lib/postgresql/data
    labels:
      - glance.parent=newsblur
      - glance.name=newsblur_db_pg

  newsblur_db_redis:
    container_name: newsblur_db_redis
    image: redis:latest
    ports:
      - 6579:6579
    restart: unless-stopped
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
      - ./docker/redis/redis_server.conf:/usr/local/etc/redis/redis_replica.conf
      - /mnt/usbssd1/data/NewsBlur/redis:/data
    command: redis-server /etc/redis/redis.conf --port 6579
    labels:
      - glance.parent=newsblur
      - glance.name=newsblur_db_redis

  # Prod Redis
  # db_redis:
  #   container_name: db_redis
  #   image: redis:latest
  #   ports:
  #     - 6579:6579
  #   restart: unless-stopped
  #   volumes:
  #     - ./docker/redis/redis.conf:/etc/redis/redis.conf
  #     - ./docker/redis/redis_server.conf:/usr/local/etc/redis/redis_replica.conf
  #     - ./docker/volumes/redis_prod:/data
  #   command: redis-server /etc/redis/redis.conf --port 6579

  newsblur_db_elasticsearch:
    container_name: newsblur_db_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    mem_limit: 1073741824
    mem_reservation: 512m
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms384m -Xmx384m -XX:UseSVE=0"
      - "CLI_JAVA_OPTS=-XX:UseSVE=0"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
      - bootstrap.memory_lock=false
      - indices.breaker.total.use_real_memory=false
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /mnt/usbssd1/data/NewsBlur/elasticsearch:/usr/share/elasticsearch/data
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    labels:
      - glance.parent=newsblur
      - glance.name=newsblur_elasticsearch

  # Dejavu is a web UI for Elasticsearch
  dejavu:
    container_name: newsblur_dejavu
    image: appbaseio/dejavu:3.6.0
    restart: unless-stopped
    ports:
      - 1358:1358
    labels:
      - glance.parent=newsblur
      - glance.name=newsblur_dejavu

  newsblur_db_mongo:
    container_name: newsblur_db_mongo
    image: mongo:4.0
    restart: unless-stopped
    ports:
      - 29019:29019
    command: mongod --port 29019 --nojournal --wiredTigerEngineConfigString="checkpoint=(wait=0),file_manager=(close_idle_time=0),verbose=(recovery_progress)"
    volumes:

      - /mnt/usbssd1/data/NewsBlur/db_mongo:/data/db:delegated
    # Ensure the MongoDB data directory has proper permissions
    user: "${CURRENT_UID:-1000}:${CURRENT_GID:-1000}"
    labels:
      - glance.parent=newsblur
      - glance.name=newsblur_mongo


  task_celery:
    container_name: newsblur_celery
    image: newsblur/newsblur_python3
    user: "${CURRENT_UID:-1000}:${CURRENT_GID:-1000}"
    command: "celery worker -A newsblur_web -B --loglevel=INFO"
    restart: unless-stopped
    volumes:
      - ${PWD}:/srv/newsblur
    environment:
      - DOCKERBUILD=True
      - HTTP_PROXY=http://172.17.0.1:8881
      - HTTPS_PROXY=http://172.17.0.1:8881
      - NO_PROXY="127.0.0.1,localhost,::1,db_postgres,db_redis,db_elasticsearch,db_mongo,nginx,haproxy,dejavu,nb.vlakor.ru,172.17.0.1,172.17.0.0/16"
    labels:
      - glance.parent=newsblur
      - glance.name=newsblur_task

  haproxy:
    container_name: newsblur_haproxy
    image: haproxy:latest
    restart: unless-stopped
    depends_on:
      - nginx
      - newsblur_web
      - newsblur_node
      - imageproxy
      - newsblur_db_redis
      - newsblur_db_postgres
      - newsblur_db_elasticsearch
      - newsblur_db_mongo
    ports:
      - 8001:80
      - 4431:443
      - 1936:1936
    volumes:
      - ./docker/haproxy/haproxy.docker-compose.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ${PWD}:/srv/newsblur
    labels:
      - glance.parent=newsblur
      - glance.name=newsblur_haproxy
